import fs from 'node:fs';
import assert from 'node:assert/strict';
const root=new URL('..',import.meta.url);
const app=fs.readFileSync(new URL('app.js',root),'utf8');
const css=fs.readFileSync(new URL('styles.css',root),'utf8');
assert.equal(app.includes('<div class="dashboard v18-general">'),false,'General Information root must not use the metric dashboard grid');
assert.equal(app.includes('<div class="v18-general">'),true,'General Information root missing');
assert.equal(app.includes('class="dashboard v18-metrics"'),true,'General Information metrics wrapper missing');
assert.match(app,/getElementsByTagNameNS\(xbrldi,'typedMember'\)/,'typedMember import support missing');
assert.match(app,/state\._v18ImportRunning=false/,'import completion flag missing');
assert.match(app,/data-v15-add/,'Add member combination markup missing');
assert.match(app,/document\.querySelectorAll\('\[data-v15-add\]'\)\.forEach/,'V18 table-action fallback binding missing');
assert.match(app,/filing-tabbar/,'Filing section navigator missing');
assert.match(css,/\.v18-general\{display:block/,'V18 general layout override missing');
assert.match(css,/\.filing-tabbar-scroll/,'Filing tab scroll layout missing');
assert.match(app,/calc-source-table/,'Calculation mapping source table UI missing');
assert.match(app,/Previous-year calculation source/,'Previous-year calculation source detail missing');
assert.match(app,/Current contribution/,'Calculation contribution detail missing');
assert.match(app,/Date fact .*yyyy-mm-dd/,'Generated XML date gate missing');
console.log('V18 UI regression checks: PASS');
