#!/usr/bin/env python3
"""V21 comprehensive regression suite.

Run with:
  python tests/v21_comprehensive_regression.py \
      --xml /path/to/charvak_1.xml \
      --xlsx /path/to/charvak_XBRL.xlsx

The XML/XLSX arguments are optional; the taxonomy/app checks run without them.
"""
from pathlib import Path
import argparse, json, re, subprocess, sys, zipfile, collections

ROOT=Path(__file__).resolve().parents[1]
fail=[]; checks=[]

def ok(name, cond, detail=""):
    checks.append((name, bool(cond), detail))
    if not cond: fail.append(f"{name}: {detail or 'failed'}")

for name in ("app.js","app-bundled.js"):
    p=ROOT/name
    r=subprocess.run(["node","--check",str(p)],capture_output=True,text=True)
    ok(f"{name} syntax",r.returncode==0,r.stderr.strip())

app=(ROOT/"app.js").read_text(encoding="utf-8")
bundled=(ROOT/"app-bundled.js").read_text(encoding="utf-8")
ok("V21 version", "APP_VERSION='21.3.0'" in app)
ok("cash-flow renderer guard", "if(!cashFlowRoleAllowed(role))" in app and "Cash-flow method is a filing-level choice" in app)
ok("cash-flow import method detection", "TypeOfCashFlowStatement" in app and "cashFactAllowed" in app)
ok("robust table action payload", "JSON.stringify(args.map" in app and "JSON.parse(decodeURIComponent" in app)
ok("generated axis inputs disabled", "Generated by software; not a user input." in app and "v15-generated-axis" in app)
ok("horizontal table engine", "v15-horizontal-table" in app and "lineHeaders" in app)
ok("no unsafe ELR-wide table fallback", "fall back to every concept in the ELR" not in app)
ok("joint-venture facts not hardcoded into table engine", "ShareLongTermBorrowingsJointVentures" not in app and "ShareShortTermBorrowingsJointVentures" not in app)
ok("V21 download name", "mca-cni-instance-v21-3.xml" in app)
ok("bundled source contains V21", "APP_VERSION='21.3.0'" in bundled)

# Extract embedded MCA_DATA from bundled JS.
try:
    idx=bundled.index("const state")
    raw=bundled[len("window.MCA_DATA="):idx].strip()
    if raw.endswith(";"): raw=raw[:-1]
    data=json.loads(raw)
except Exception as e:
    data={}
    fail.append(f"embedded taxonomy parse: {e}")

defs=data.get("definitions",[])
els={f"{e['prefix']}:{e['name']}":e for e in data.get("elements",[])}
roles=sorted({d.get("role") for d in defs})
models=[]
for role in roles:
    ds=[d for d in defs if d.get("role")==role]
    tables=[d for d in ds if d.get("nodeType")=="table" and not str(d.get("name","")).endswith("NotAll")]
    for t in tables:
        base=str(t["name"])[:-5] if str(t["name"]).endswith("Table") else str(t["name"])
        ln=next((d for d in ds if d.get("name")==base+"LineItems"),None)
        if not ln:
            ti=ds.index(t); td=t.get("depth",0)
            for r in ds[ti+1:]:
                if r.get("nodeType")=="lineItems" or str(r.get("name","")).endswith("LineItems"):
                    ln=r; break
                if r.get("depth",0)<=td: break
        axes=[d for d in ds if d.get("nodeType")=="axis" and d.get("depth")==t.get("depth",0)+1]
        lis=[]
        if ln:
            li=ds.index(ln); ld=ln.get("depth",0)
            for r in ds[li+1:]:
                if r.get("depth",0)<=ld: break
                if r.get("nodeType")=="concept":
                    q=f"{r['prefix']}:{r['name']}"
                    if q not in lis: lis.append(q)
        models.append({"role":role,"table":f"{t['prefix']}:{t['name']}","axes":[f"{a['prefix']}:{a['name']}" for a in axes],"lineItems":lis})
ok("92 taxonomy table models",len(models)==92,f"found {len(models)}")
ok("all taxonomy tables have line items",all(m["lineItems"] for m in models),
   f"{sum(not m['lineItems'] for m in models)} tables have none")

def getmodel(q):
    return next((m for m in models if m["table"]==q),None)

expected={
"in-gaap:DisclosureOfShareholdingMoreThanFivePerCentInCompanyTable":(
    ["in-gaap:ClassesOfShareCapitalAxis","in-gaap:NameOfShareholderAxis"],7),
"in-ca:DisclosureOfPrincipalProductOrServicesTable":(
    ["in-ca:TypesOfPrincipalProductOrServicesAxis"],8),
"in-ca:DisclosureOfKeyManagerialPersonnelsAndDirectorsAndRemunerationToKeyManagerialPersonnelsAndDirectorsTable":(
    ["in-ca:KeyManagerialPersonnelsAndDirectorsAxis"],19),
"in-gaap:DetailsOfGoodsPurchasedTable":(
    ["in-gaap:CategoriesOfGoodsPurchasedAxis"],2),
"in-gaap:DetailsOfRawMaterialsConsumedTable":(
    ["in-gaap:CategoriesOfRawMaterialsConsumedAxis"],2),
"in-gaap:ClassificationOfBorrowingsTable":(
    ["in-gaap:ClassificationBasedOnTimePeriodAxis","in-gaap:ClassificationOfBorrowingsAxis","in-gaap:SubclassificationOfBorrowingsAxis"],10),
}
for q,(axes,n) in expected.items():
    m=getmodel(q)
    ok(q+" model",m is not None,f"missing")
    if m:
        ok(q+" axes",m["axes"]==axes,f"{m['axes']}")
        ok(q+" line items",len(m["lineItems"])==n,f"found {len(m['lineItems'])}")
        if "Borrowings" in q:
            ok("borrowings excludes JV standalone facts",
               "in-gaap:ShareLongTermBorrowingsJointVentures" not in m["lineItems"] and
               "in-gaap:ShareShortTermBorrowingsJointVentures" not in m["lineItems"])

# Workbook and XML tests.
ap=argparse.ArgumentParser()
ap.add_argument("--xml")
ap.add_argument("--xlsx")
args=ap.parse_args()

if args.xlsx:
    try:
        from openpyxl import load_workbook
        wb=load_workbook(args.xlsx,data_only=False,read_only=True)
        sheet_names=wb.sheetnames
        workbook_table_ids={str(wb[n]["K2"].value) for n in sheet_names if wb[n]["K2"].value}
        for q in expected:
            short=q.split(":")[-1]
            ok("workbook table "+short,short in workbook_table_ids,f"not found in K2 table identifiers")
        for sheet,need in {
            "ShareholdingMorThnFivePerCent":["DisclosureOfShareholdingMoreThanFivePerCentInCompanyTable"],
            "ProductServiceDetails":["DisclosureOfPrincipalProductOrServicesTable"],
            "RawMaterialsConsumed":["DetailsOfRawMaterialsConsumedTable"],
            "GoodsPurchased":["DetailsOfGoodsPurchasedTable"],
            "ClassificationOfBorrowings":["ClassificationOfBorrowingsTable"],
        }.items():
            ok("workbook "+sheet,sheet in sheet_names)
            if sheet in sheet_names:
                ws=wb[sheet]
                ok("workbook "+sheet+" header",ws["K2"].value in need,f"K2={ws['K2'].value}")
        if "CashFlowDirect" in sheet_names and "CashFlowIndirect" in sheet_names:
            ok("workbook has separate cash-flow sheets",True)
    except Exception as e: fail.append(f"workbook inspection: {e}")

if args.xml:
    try:
        from lxml import etree
        root=etree.parse(args.xml).getroot()
        XBRLI="http://www.xbrl.org/2003/instance"; XBRLDI="http://xbrl.org/2006/xbrldi"
        contexts=root.xpath("//xbrli:context",namespaces={"xbrli":XBRLI})
        facts=[x for x in root if x.tag.startswith("{") and x.tag.split("}")[-1] not in ("context","unit","schemaRef","footnoteLink")]
        method=[(x.text or "").strip() for x in facts if x.tag.split("}")[-1]=="TypeOfCashFlowStatement"]
        ok("XML cash-flow method detected",any("indirect" in x.lower() for x in method),str(method))
        ok("XML contexts",len(contexts)==413,f"{len(contexts)}")
        ok("XML facts",len(facts)==3939,f"{len(facts)}")
        # Count typed/explicit table rows for key tables by concept+dimension axes.
        uri_prefix={
          "http://www.icai.org/xbrl/taxonomy/2016-03-31/in-gaap":"in-gaap",
          "http://www.icai.org/xbrl/taxonomy/2016-03-31/in-ca":"in-ca"}
        def qname(tag):
            if not tag.startswith("{"): return tag
            u,l=tag[1:].split("}",1); return f"{uri_prefix.get(u,u)}:{l}"
        cinfo={}
        for c in contexts:
            dims=[]
            for d in c.xpath(".//xbrldi:explicitMember",namespaces={"xbrldi":XBRLDI}):
                dims.append((d.get("dimension"),"explicit",(d.text or "").strip()))
            for d in c.xpath(".//xbrldi:typedMember",namespaces={"xbrldi":XBRLDI}):
                ch=next(iter(d)); dims.append((d.get("dimension"),"typed",(ch.text or "").strip()))
            p=c.xpath("./xbrli:period",namespaces={"xbrli":XBRLI})[0]
            ed=p.xpath("./xbrli:endDate",namespaces={"xbrli":XBRLI})
            ins=p.xpath("./xbrli:instant",namespaces={"xbrli":XBRLI})
            cinfo[c.get("id")]={"dims":dims,"year":int((ed[0].text if ed else ins[0].text)[:4])}
        latest=max(c["year"] for c in cinfo.values())
        rowsets=collections.defaultdict(set)
        for f in facts:
            c=cinfo.get(f.get("contextRef"))
            if not c or c["year"]!=latest or not c["dims"]: continue
            q=qname(f.tag); axes={d[0] for d in c["dims"]}
            for m in models:
                if q in m["lineItems"] and set(m["axes"])==axes:
                    rowsets[m["table"]].add(tuple(c["dims"]))
        ok("shareholding imported rows",len(rowsets["in-gaap:DisclosureOfShareholdingMoreThanFivePerCentInCompanyTable"])==5,
           str(len(rowsets["in-gaap:DisclosureOfShareholdingMoreThanFivePerCentInCompanyTable"])))
        ok("principal product/service imported rows",len(rowsets["in-ca:DisclosureOfPrincipalProductOrServicesTable"])==1,
           str(len(rowsets["in-ca:DisclosureOfPrincipalProductOrServicesTable"])))
        ok("KMP/director imported rows",len(rowsets["in-ca:DisclosureOfKeyManagerialPersonnelsAndDirectorsAndRemunerationToKeyManagerialPersonnelsAndDirectorsTable"])==2,
           str(len(rowsets["in-ca:DisclosureOfKeyManagerialPersonnelsAndDirectorsAndRemunerationToKeyManagerialPersonnelsAndDirectorsTable"])))
    except Exception as e: fail.append(f"XML inspection: {e}")

print(f"Checks: {len(checks)}")
for n,p,d in checks:
    print(("PASS" if p else "FAIL")+"  "+n+(f" — {d}" if d and not p else ""))
if fail:
    print("\nFAILURES")
    print("\n".join("- "+x for x in fail))
    sys.exit(1)
print("PASS: V21 comprehensive regression suite")
