import fs from 'node:fs'; import vm from 'node:vm';
const root=new URL('..',import.meta.url);
const bundle=fs.readFileSync(new URL('app-bundled.js',root),'utf8').replace(/\nload\(\);\s*$/,'\n');
const els=new Map();
const el=id=>{if(!els.has(id))els.set(id,{id,innerHTML:'',value:'',dataset:{},style:{},classList:{add(){},remove(){},contains(){return false}},addEventListener(){},querySelector(){return null},querySelectorAll(){return []}});return els.get(id)};
const documentStub={getElementById:el,querySelectorAll(){return []},querySelector(){return null},createElement:tag=>el(tag),addEventListener(){}};
const ctx={window:{addEventListener(){}},document:documentStub,localStorage:{getItem(){return null},setItem(){},removeItem(){}},console,Blob:function(){},URL:{createObjectURL(){return ''},revokeObjectURL(){}},setInterval,clearInterval,setTimeout,clearTimeout,performance:{now:()=>Date.now()},confirm:()=>true,FileReader:function(){},DOMParser:function(){},XMLSerializer:function(){},TextEncoder,TextDecoder,btoa:s=>Buffer.from(s,'binary').toString('base64'),atob:s=>Buffer.from(s,'base64').toString('binary'),unescape,encodeURIComponent};
vm.createContext(ctx); vm.runInContext(bundle,ctx,{timeout:120000}); ctx.MCA_DATA=ctx.window.MCA_DATA;
const result=vm.runInContext(`(()=>{
  Object.assign(state,{meta:MCA_DATA.meta,elements:MCA_DATA.elements,presentation:MCA_DATA.presentation,calculations:MCA_DATA.calculations,definitions:MCA_DATA.definitions,rules:MCA_DATA['business-rules'],elrs:MCA_DATA.elrs,values:{},prior:{},contexts:[],units:[],dimTables:{},profile:{cin:'',companyName:'',fyStart:'2025-04-01',fyEnd:'2026-03-31',currency:'Indian rupee',firstYear:false,financialStatements:'Standalone',inputScale:'Actuals',generalInfoEnabled:true,cashFlowMethod:''}});
  normalizeState();
  const control=state.elements.find(e=>e.name==='WhetherThereAreAnyRelatedPartyTransactionsDuringYear');
  const ck=control.prefix+':'+control.name;
  state.values[ck]='false';
  const model=v15AllTableModels().find(m=>m.name==='DisclosureOfRelationshipAndTransactionsBetweenRelatedPartiesTable');
  const tableDisabled=v22TableApplicable(v22TableHostRole(model),model,'current')===false;
  const dependent=state.elements.find(e=>e.name==='NameOfRelatedParty');
  const dk=dependent.prefix+':'+dependent.name;
  const fieldDisabled=isDisabledConcept(dk,dependent,'[201601]',false);
  state.values[ck]='true';
  const tableEnabled=v22TableApplicable(v22TableHostRole(model),model,'current')===true;
  return {tableDisabled,fieldDisabled,tableEnabled,controller:ck};
})()`,ctx,{timeout:120000});
if(!result.tableDisabled||!result.fieldDisabled||!result.tableEnabled)throw new Error(JSON.stringify(result));
console.log('PASS: related-party No disables dependent table/fields; Yes enables them:',JSON.stringify(result));
